apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rdma-device-plugin-daemonset
  namespace: kube-system
  labels:
    k8s-app: rdma-device-plugin-daemonset
spec:
  selector:
    matchLabels:
      k8s-app: rdma-device-plugin-daemonset
  template:
    metadata:
      labels:
        k8s-app: rdma-device-plugin-daemonset
    spec:
      tolerations:
      # Allow this pod to be rescheduled while the node is in "critical add-ons only" mode.
      # This, along with the annotation above marks this pod as a critical add-on.
      - key: CriticalAddonsOnly
        operator: Exists
      hostNetwork: true
      containers:
      - image: carmark/k8s-rdma-device-plugin:latest
        imagePullPolicy: IfNotPresent
        name: rdma-device-plugin-ctr
        #args: ["-log-level", "debug"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
